# Challenge 2.2 - Dictionnaires et Tuples
# Votre code ici...

# Challenge 3.1 - Lambda et fonctions d'ordre supérieur
# Votre code ici...

# Challenge 4.1 - Classes et objets
# Votre code ici...

# Challenge 5.1 - Gestion des exceptions
# Votre code ici...
